import numpy as np
import pandas as pd
import glob
import os
import re
import shutil
import statistics as st
import scipy.stats as sci_st
from texttable import Texttable
import sys
from scipy.stats import entropy

# import local libraries
sys.path.insert(0, os.path.dirname(__file__)+'/../tools/')
import DS_fns as ds_fns
import table_utils as tb_utils
import sys_utils
# extract currenty directory name for path adjustification
dirname = os.path.dirname(__file__)+'/..'


title_dict = {
'AX_DR_coverage_percent'       : 'Ax DR Coverage',
'AY_DR_coverage_percent'       : 'Ay DR Coverage',
'AZ_DR_coverage_percent'       : 'Az DR Coverage',
'GX_DR_coverage_percent'       : 'Gx DR Coverage',
'GY_DR_coverage_percent'       : 'Gy DR Coverage',
'GZ_DR_coverage_percent'       : 'Gz DR Coverage',
'AX_DR_limit_count'            : 'Ax DR Crossing',
'AX_DR_limit_percent'          : 'Ax DR Crossing',
'AY_DR_limit_count'            : 'Ay DR Crossing',
'AY_DR_limit_percent'          : 'Ay DR Crossing',
'AZ_DR_limit_count'            : 'Az DR Crossing',
'AZ_DR_limit_percent'          : 'Az DR Crossing',
'GX_DR_limit_count'            : 'Gx DR Crossing',
'GX_DR_limit_percent'          : 'Gx DR Crossing',
'GY_DR_limit_count'            : 'Gy DR Crossing',
'GY_DR_limit_percent'          : 'Gy DR Crossing',
'GZ_DR_limit_count'            : 'Gz DR Crossing',
'GZ_DR_limit_percent'          : 'Gz DR Crossing',
'AX'                           : 'Ax',
'AY'                           : 'Ay',
'AZ'                           : 'Az',
'GX'                           : 'Gx',
'GY'                           : 'Gy',
'GZ'                           : 'Gz',
'AX_1ST_DIFF'                  : '$d Ax/ dt$',
'AY_1ST_DIFF'                  : '$d Ay/ dt$',
'AZ_1ST_DIFF'                  : '$d Az/ dt$',
'GX_1ST_DIFF'                  : '$d Gx/ dt$',
'GY_1ST_DIFF'                  : '$d Gy/ dt$',
'GZ_1ST_DIFF'                  : '$d Gz/ dt$',
'AX_2ND_DIFF'                  : '$d Ax^2/ dt^2$',
'AY_2ND_DIFF'                  : '$d Ay^2/ dt^2$',
'AZ_2ND_DIFF'                  : '$d Az^2/ dt^2$',
'GX_2ND_DIFF'                  : '$d Gx^2/ dt^2$',
'GY_2ND_DIFF'                  : '$d Gy^2/ dt^2$',
'GZ_2ND_DIFF'                  : '$d Gz^2/ dt^2$',
'ACC_MAG'                      : 'Acc. Magnitude',
'ROT_ONLY_COUNT'               : 'Rotation Only Motion',
'ROT_ONLY_PERCENT'             : 'Rotation Only Motion',
'BLACK_EXPOSURE_COUNT'         : 'Black Exposure',
'BLACK_EXPOSURE_PERCENT'       : 'Black Exposure',
'WHITE_EXPOSURE_COUNT'         : 'White Exposure',
'WHITE_EXPOSURE_PERCENT'       : 'White Exposure',
'OVER_EXPOSURE_COUNT'          : 'Over Exposure',
'OVER_EXPOSURE_PERCENT'        : 'Over Exposure',
'PROPER_EXPOSURE_COUNT'        : 'Proper Exposure',
'PROPER_EXPOSURE_PERCENT'      : 'Proper Exposure',
'UNDER_EXPOSURE_COUNT'         : 'Under Exposure',
'UNDER_EXPOSURE_PERCENT'       : 'Under Exposure',
'EXPOSURE_MEAN'                : 'Exposure Img. Mean',
'EXPOSURE_SKEW'                : 'Exposure Img. Skewness',
'EXPOSURE_ZONE'                : 'Exposure Zone',
'BLUR_PERCENT'                 : 'Blurring Percentage ',
'BLUR_SCORE'                   : 'Blurring Score',
'BLUR_LOCAL_COUNT'             : 'Local Blurring ($>$0\%)',
'BLUR_LOCAL_PERCENT'           : 'Local Blurring ($>$0\%)',
'BLUR_TOTAL_COUNT'             : 'Blurred Images ($>$ 50\%)',
'BLUR_TOTAL_PERCENT'           : 'Blurred Images ($>$ 50\%)',
'BLUR_GLOBAL_COUNT'            : 'Global Blurring ($>$90\%)',
'BLUR_GLOBAL_PERCENT'          : 'Global Blurring ($>$90\%)',
'BRIGHTNESS'                   : 'Brightness',
'BRIGHTNESS_DIFF'              : 'd Br/dt',
'BRIGHTNESS_DIFF_1SIGMA'       : 'd Br/d $>$ 1$\sigma$',
'BRIGHTNESS_DIFF_1SIGMA_RATIO' : 'd Br/d $>$ 1$\sigma$',
'BRIGHTNESS_DIFF_2SIGMA'       : 'd Br/d $>$ 2$\sigma$',
'BRIGHTNESS_DIFF_2SIGMA_RATIO' : 'd Br/d $>$ 2$\sigma$',
'BRIGHTNESS_DIFF_3SIGMA'       : 'd Br/d $>$ 3$\sigma$',
'BRIGHTNESS_DIFF_3SIGMA_RATIO' : 'd Br/d $>$ 3$\sigma$',
'DISPARITY_AVG_BM'             : 'Disparity Mean (BM)',
'DISPARITY_AVG_SGBM'           : 'Disparity Mean (SGBM)',
'DISPARITY_MAX_BM'             : 'Disparity Max. (BM)',
'DISPARITY_MAX_SGBM'           : 'Disparity Max. (SGBM)',
'DISPARITY_MIN_BM'             : 'Disparity Min. (BM)',
'DISPARITY_MIN_SGBM'           : 'Disparity Min. (SGBM)',
'DISPARITY_STD_DIV_BM'         : 'Disparity Std. Dev. (BM)',
'DISPARITY_STD_DIV_SGBM'       : 'Disparity Std. Dev. (SGBM)',
'CONTRAST_CR'                  : 'Contrast Ratio',
'CONTRAST_MICHELSON'           : 'Michelson Contrast Score',
'CONTRAST_RMS'                 : 'RMS Contrast Score',
'CONTRAST_WEBER'               : 'Weber Contrast Score',
'REVISIT_DIST'                 : 'Dist to Closest Match',
'REVISIT_SCORE'                : 'Image Similarity Score',
'REVISIT_SCORE_0P5'            : 'Image Similarity Score $>$ 0.5',
'REVISIT_SCORE_0P9'            : 'Image Similarity Score $>$ 0.9',
'REVISIT_SCORE_1P0'            : 'Image Similarity Score = 1',
'SIFT_COUNT'                   : 'No. SIFT Features',
'ORB_COUNT'                    : 'No. ORB Features',
'FAST_COUNT'                   : 'No. FAST Features',
'SIFT_DIST_ABS'                : 'Abs. Spatial Dist. - SIFT',
'ORB_DIST_ABS'                 : 'Abs. Spatial Dist. - ORB',
'FAST_DIST_ABS'                : 'Abs. Spatial Dist. - FAST',
'SIFT_DIST_AVG'                : 'Avg. Spatial Dist. - SIFT',
'ORB_DIST_AVG'                 : 'Avg. Spatial Dist.- ORB',
'FAST_DIST_AVG'                : 'Avg. Spatial Dist. - FAST',
'RGB_CAM_L_SEQ_COUNT'          : 'No. Seq. (RGB - L)',
'RGB_CAM_R_SEQ_COUNT'          : 'No. Seq. (RGB - R)',
'IMU_SEQ_COUNT'                : 'No. Seq. (IMU)',
'RGB_CAM_L_SAMPLES_COUNT'      : 'Samples (RGB - L)',
'RGB_CAM_R_SAMPLES_COUNT'      : 'Samples (RGB - R)',
'IMU_SAMPLES_COUNT'            : 'Samples (IMU)',
'RGB_CAM_L_DURATION'           : 'Seq. Duration (RGB - L)',
'RGB_CAM_R_DURATION'           : 'Seq. Duration (RGB - R)',
'IMU_DURATION'                 : 'Seq. Duration (IMU)',
'RGB_CAM_L_SAMPLE_RATE'        : 'Sample Time (RGB - L)',
'RGB_CAM_R_SAMPLE_RATE'        : 'Sample Time (RGB - R)',
'IMU_SAMPLE_RATE'              : 'Sample Time (IMU)',
'VI_TIMESTAMP_MISMATCH'        : 'V-I TS Mismatch',
}

units_dict = {
'AX_DR_coverage_percent'       : '\%',
'AY_DR_coverage_percent'       : '\%',
'AZ_DR_coverage_percent'       : '\%',
'GX_DR_coverage_percent'       : '\%',
'GY_DR_coverage_percent'       : '\%',
'GZ_DR_coverage_percent'       : '\%',
'AX_DR_limit_count'            : 'Samples',
'AX_DR_limit_percent'          : '\%',
'AY_DR_limit_count'            : 'Samples',
'AY_DR_limit_percent'          : '\%',
'AZ_DR_limit_count'            : 'Samples',
'AZ_DR_limit_percent'          : '\%',
'GX_DR_limit_count'            : 'Samples',
'GX_DR_limit_percent'          : '\%',
'GY_DR_limit_count'            : 'Samples',
'GY_DR_limit_percent'          : '\%',
'GZ_DR_limit_count'            : 'Samples',
'GZ_DR_limit_percent'          : '\%',
'AX'                           : 'm/sec^2',
'AY'                           : 'm/sec^2',
'AZ'                           : 'm/sec^2',
'GX'                           : 'deg/sec',
'GY'                           : 'deg/sec',
'GZ'                           : 'deg/sec',
'AX_1ST_DIFF'                  : 'm/sec^3',
'AY_1ST_DIFF'                  : 'm/sec^3',
'AZ_1ST_DIFF'                  : 'm/sec^3',
'GX_1ST_DIFF'                  : 'deg/sec^2',
'GY_1ST_DIFF'                  : 'deg/sec^2',
'GZ_1ST_DIFF'                  : 'deg/sec^2',
'AX_2ND_DIFF'                  : 'm/sec^4',
'AY_2ND_DIFF'                  : 'm/sec^4',
'AZ_2ND_DIFF'                  : 'm/sec^4',
'GX_2ND_DIFF'                  : 'deg/sec^4',
'GY_2ND_DIFF'                  : 'deg/sec^4',
'GZ_2ND_DIFF'                  : 'deg/sec^4',
'ACC_MAG'                      : 'm/sec^2',
'ROT_ONLY_COUNT'               : 'Samples',
'ROT_ONLY_PERCENT'             : '\%',
'BLACK_EXPOSURE_COUNT'         : 'Samples',
'BLACK_EXPOSURE_PERCENT'       : '\%',
'WHITE_EXPOSURE_COUNT'         : 'Samples',
'WHITE_EXPOSURE_PERCENT'       : '\%',
'OVER_EXPOSURE_COUNT'          : 'Samples',
'OVER_EXPOSURE_PERCENT'        : '\%',
'PROPER_EXPOSURE_COUNT'        : 'Samples',
'PROPER_EXPOSURE_PERCENT'      : '\%',
'UNDER_EXPOSURE_COUNT'         : 'Samples',
'UNDER_EXPOSURE_PERCENT'       : '\%',
'EXPOSURE_MEAN'                : 'DL',
'EXPOSURE_SKEW'                : 'DL',
'EXPOSURE_ZONE'                : 'DL',
'BLUR_PERCENT'                 : '\%',
'BLUR_SCORE'                   : 'DL',
'BLUR_LOCAL_COUNT'             : 'Samples',
'BLUR_LOCAL_PERCENT'           : '\%',
'BLUR_TOTAL_COUNT'             : 'Samples',
'BLUR_TOTAL_PERCENT'           : '\%',
'BLUR_GLOBAL_COUNT'            : 'Samples',
'BLUR_GLOBAL_PERCENT'          : '\%',
'BRIGHTNESS'                   : 'DL',
'BRIGHTNESS_DIFF'              : 'DL',
'BRIGHTNESS_DIFF_1SIGMA'       : 'Samples',
'BRIGHTNESS_DIFF_1SIGMA_RATIO' : '\%',
'BRIGHTNESS_DIFF_2SIGMA'       : 'Samples',
'BRIGHTNESS_DIFF_2SIGMA_RATIO' : '\%',
'BRIGHTNESS_DIFF_3SIGMA'       : 'Samples',
'BRIGHTNESS_DIFF_3SIGMA_RATIO' : '\%',
'DISPARITY_AVG_BM'             : 'DL',
'DISPARITY_AVG_SGBM'           : 'DL',
'DISPARITY_MAX_BM'             : 'DL',
'DISPARITY_MAX_SGBM'           : 'DL',
'DISPARITY_MIN_BM'             : 'DL',
'DISPARITY_MIN_SGBM'           : 'DL',
'DISPARITY_STD_DIV_BM'         : 'DL',
'DISPARITY_STD_DIV_SGBM'       : 'DL',
'CONTRAST_CR'                  : 'DL',
'CONTRAST_MICHELSON'           : 'DL',
'CONTRAST_RMS'                 : 'DL',
'CONTRAST_WEBER'               : 'DL',
'REVISIT_DIST'                 : 'Samples',
'REVISIT_SCORE'                : 'DL',
'REVISIT_SCORE_0P5'            : 'DL',
'REVISIT_SCORE_0P9'            : 'DL',
'REVISIT_SCORE_1P0'            : 'DL',
'SIFT_COUNT'                   : 'Features',
'ORB_COUNT'                    : 'Features',
'FAST_COUNT'                   : 'Features',
'SIFT_DIST_ABS'                : '\%',
'ORB_DIST_ABS'                 : '\%',
'FAST_DIST_ABS'                : '\%',
'SIFT_DIST_AVG'                : '\%',
'ORB_DIST_AVG'                 : '\%',
'FAST_DIST_AVG'                : '\%',
'RGB_CAM_L_SEQ_COUNT'          : 'Sequence',
'RGB_CAM_R_SEQ_COUNT'          : 'Sequence',
'IMU_SEQ_COUNT'                : 'Sequence',
'RGB_CAM_L_SAMPLES_COUNT'      : 'Samples',
'RGB_CAM_R_SAMPLES_COUNT'      : 'Samples',
'IMU_SAMPLES_COUNT'            : 'Samples',
'RGB_CAM_L_DURATION'           : 'sec',
'RGB_CAM_R_DURATION'           : 'sec',
'IMU_DURATION'                 : 'sec',
'RGB_CAM_L_SAMPLE_RATE'        : 'sec',
'RGB_CAM_R_SAMPLE_RATE'        : 'sec',
'IMU_SAMPLE_RATE'              : 'sec',
'VI_TIMESTAMP_MISMATCH'        : 'sec',
}

sys_utils.export_dict(dirname+"/../out_data/agg_reports/dicts/", "titles_dict", title_dict)
sys_utils.export_dict(dirname+"/../out_data/agg_reports/dicts/", "units_dict", units_dict)

inertial_tags = [
'AX',
'AY',
'AZ',
'GX',
'GY',
'GZ',
'AX_1ST_DIFF',
'AY_1ST_DIFF',
'AZ_1ST_DIFF',
'GX_1ST_DIFF',
'GY_1ST_DIFF',
'GZ_1ST_DIFF',
'AX_2ND_DIFF',
'AY_2ND_DIFF',
'AZ_2ND_DIFF',
'GX_2ND_DIFF',
'GY_2ND_DIFF',
'GZ_2ND_DIFF',
'AX_DR_coverage_percent',
'AY_DR_coverage_percent',
'AZ_DR_coverage_percent',
'GX_DR_coverage_percent',
'GY_DR_coverage_percent',
'GZ_DR_coverage_percent',
'ACC_MAG',
'ROT_ONLY_PERCENT'
]

general_tags =[
'RGB_CAM_L_SAMPLES_COUNT',
'RGB_CAM_R_SAMPLES_COUNT',
'IMU_SAMPLES_COUNT',
'RGB_CAM_L_DURATION',
'RGB_CAM_R_DURATION',
'IMU_DURATION',
'RGB_CAM_L_SAMPLE_RATE',
'RGB_CAM_R_SAMPLE_RATE',
'IMU_SAMPLE_RATE',
'VI_TIMESTAMP_MISMATCH'
]

visual_tags = [
'BRIGHTNESS',
'BRIGHTNESS_DIFF',
'BRIGHTNESS_DIFF_1SIGMA_RATIO',
'BRIGHTNESS_DIFF_2SIGMA_RATIO',
'BRIGHTNESS_DIFF_3SIGMA_RATIO',
'BLACK_EXPOSURE_PERCENT',
'WHITE_EXPOSURE_PERCENT',
'OVER_EXPOSURE_PERCENT',
'PROPER_EXPOSURE_PERCENT',
'UNDER_EXPOSURE_PERCENT',
'EXPOSURE_MEAN',
'EXPOSURE_SKEW',
'EXPOSURE_ZONE',
'CONTRAST_CR',
'CONTRAST_WEBER',
'CONTRAST_MICHELSON',
'CONTRAST_RMS',
'BLUR_PERCENT',
'BLUR_SCORE',
'BLUR_LOCAL_PERCENT',
'BLUR_TOTAL_PERCENT',
'BLUR_GLOBAL_PERCENT',
'SIFT_COUNT',
'SIFT_DIST_ABS',
'SIFT_DIST_AVG',
'ORB_COUNT',
'ORB_DIST_ABS',
'ORB_DIST_AVG',
'FAST_COUNT',
'FAST_DIST_ABS',
'FAST_DIST_AVG',
'DISPARITY_AVG_BM',
'DISPARITY_STD_DIV_BM',
'DISPARITY_AVG_SGBM',
'DISPARITY_STD_DIV_SGBM',
'REVISIT_DIST',
'REVISIT_SCORE'
]